name: CI

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  terraform-and-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ---------- Python tests ----------
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install pytest
        run: pip install pytest

      - name: Run create lambda tests
        working-directory: src/create-url-lambda
        run: pytest -q

      - name: Run retrieve lambda tests
        working-directory: src/retrieve-url-lambda
        run: pytest -q

      # ---------- Terraform checks ----------
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.5"

      - name: Terraform fmt
        run: terraform fmt -check -recursive

      - name: Terraform init (no backend)
        working-directory: terraform/env/dev
        run: terraform init -backend=false

      - name: Terraform validate
        working-directory: terraform/env/dev
        run: terraform validate
